[package]
name = "proc-macro-error"
version = "1.0.2"
authors = ["CreepySkeleton <creepy-skeleton@yandex.ru>"]
description = "Almost drop-in replacement to panics in proc-macros"

repository = "https://gitlab.com/CreepySkeleton/proc-macro-error"
readme = "README.md"
keywords = ["proc-macro", "error", "errors"]
categories = ["development-tools::procedural-macro-helpers"]
license = "MIT OR Apache-2.0"

edition = "2018"
build = "build.rs"

[badges]
maintenance = { status = "passively-maintained" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
quote = "1"
proc-macro2 = "1"
syn = { version = "1", default-features = false, features = ["derive", "parsing", "proc-macro", "printing"] }
proc-macro-error-attr = { path = "./proc-macro-error-attr", version = "=1.0.2"}

[dev-dependencies]
test-crate = { path = "./test-crate" }
proc-macro-hack-test = { path = "./test-crate/proc-macro-hack-test" }
trybuild = { version = "1.0.19", features = ["diff"] }
toml = "=0.5.2" # DO NOT BUMP
serde_derive = "=1.0.110" # DO NOT BUMP

[build-dependencies]
version_check = "0.9"
